### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ZeroIntensity** [ofek/hatch-mypyc#20]
i recently created [#947](https://github.com/mypyc/mypyc/issues/947) on the mypyc repo.

i'm not too optimistic in them helping on this, so i was wondering if you maybe had any other ideas? it seems that this might be a hatch-mypyc issue in the first place.

**Comment by ofek** [comment]
The package directory differs from the project name https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection

Add:

```toml
[build.targets.wheel]
packages = ["src/repro"]
```

**Comment by ZeroIntensity** [comment]
ah, ty

**Comment by ofek** [comment]
Anytime!
