### ISSUE TITLE
Hatch-mypyc uses the building platform during cross-compilation, not the target platform (`_PYTHON_HOST_PLATFORM`)

### ISSUE THREAD

**Issue by ichard26** [ofek/hatch-mypyc#24]
Hey, so Black uses hatch-mypyc. It's great and we're happy we can finally use modern packaging standards! Unfortunately, it broke our cross-architecture macOS builds. When using CIBW to build universal2 and arm64 wheels for macOS, the wheels end up with the wrong platform tag. [For example, here they are labelled to support x86_64, but they're arm64 wheels in reality.](https://github.com/psf/black/actions/runs/3200959148/jobs/5228454073#step:3:693)

Setuptools labels the wheels correctly. [Hatchling only supports inferring the platform tag for the machine the build is taking place on](https://github.com/pypa/hatch/blob/c879e33400fd25ce259d7bfde00fbf7c1c2ee8bb/backend/src/hatchling/builders/wheel.py#L326-L332) and ignores `_PYTHON_HOST_PLATFORM` (which [CIBW sets during a cross-platform macOS build](https://github.com/pypa/cibuildwheel/blob/2e6cbe2435ef410156319c98625002ed76e08785/cibuildwheel/macos.py#L219-L232)).

<details>

<summary>My best guess at how setuptools selects the right platform tag during cross-compilation</summary>

- Digging through the setuptools codebase, I'll guess that it uses `sysconfig.get_platform()` [which looks at `_PYTHON_HOST_PLATFORM` here](https://github.com/python/cpython/blob/504e12272b19395a3c59631a20a94e3323af78e5/Lib/sysconfig.py#L774).

- The wheel name is derived from `Wheel.egg_name()` [which calls `distutils.util.get_platform()`](https://github.com/pypa/setuptools/blob/c75928017022ac52464ed65e9fe3a553281372fc/setuptools/wheel.py#L94) assuming it isn't any already.

- [`distutils.util.get_platform()` calls `distutils.util.get_host_platform()`](https://github.com/pypa/setuptools/blob/c75928017022ac52464ed65e9fe3a553281372fc/setuptools/_distutils/util.py#L60
)

- [`distutils.util.get_host_platform()` calls `sysconfig.get_platform()`](https://github.com/pypa/setuptools/blob/c75928017022ac52464ed65e9fe3a553281372fc/setuptools/_distutils/util.py#L48) which as noted, checks `_PYTHON_HOST_PLATFORM`

Figuring out where the platform tags stored in .dist-info come from isn't nearly as obvious -- I barely know the setuptools codebase 

</details>

I did not catch this issue while reviewing the original PR so this affected the 22.10.0 release (https://github.com/psf/black/issues/3312). In the interim, I'm fixing the wheel platform tags by hand before publishing them to PyPI. It works, but it isn't ideal :slightly_smiling_face: 

cc @zsol since he is way more knowledgeable about this kind of stuff than me

**Comment by ofek** [comment]
related: https://github.com/PyO3/maturin/issues/1289

**Comment by ofek** [comment]
from @henryiii:

https://github.com/scikit-build/scikit-build-core/blob/e9a6e97a0ae7ffffcb5c3756112b2a59339bb4ef/src/scikit_build_core/builder/builder.py#L51-L55 is how I do it. 

ARCHFLAGS is how setuptools targets other arch’s and cibuildwheel and conda set it.
