### ISSUE TITLE
Update for mypy 1.0?

### ISSUE THREAD

**Issue by bollwyvl** [ofek/hatch-mypyc#30]
Thanks for this package.

With mypy 1.0.0 out, the `~` operator doesn't allow this package to be installed together with the new version. I don't know what is entailed in upgrading, or how long the pre 1.0 versions would need to be supported, but it would be lovely to have a compatible version.

**Comment by ofek** [comment]
Oh good idea! Would you mind making a PR?

**Comment by ofek** [comment]
`~` -> `>=`
